language: python
python:
  - 2.7
  
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:team-electronics/ppa
  - sudo apt-get update

install:
  - sudo apt-get -y install iverilog-daily  
  - sudo apt-get install -qq libhdf5-serial-dev
  
  #conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - conda install --yes numpy bitarray pytest pyyaml 
  
  #cocotb
  - git clone https://github.com/potentialventures/cocotb.git
  - export COCOTB=$(pwd)/cocotb
  
  # Install basil  
  - git clone -b development https://github.com/SiLab-Bonn/basil; cd basil; python setup.py develop; cd ..;

  # Install tlu
  - python setup.py develop
  
script:
  - cd tests;  py.test -s

