name: Software tests

on: push

jobs:
  tests:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Set up Anaconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.9
    - name: Install Conda dependencies
      shell: bash -l {0}
      run: |
        conda info -a
        conda install pytest numpy psutil qtpy pyyaml pyzmq pytables
    - name: Install basil
      shell: bash -l {0}
      run: |
        pip install basil-daq>=3.0.0
    - name: Install Python dependencies
      shell: bash -l {0}
      run: |
        pip install cocotb cocotb_bus xvfbwrapper pyqt5
    - name: Install iverilog
      run: |
        sudo apt-get install -qq libhdf5-serial-dev
        # sudo apt-get -y install iverilog-daily
        sudo apt-get install gperf
        git clone https://github.com/steveicarus/iverilog.git
        cd iverilog; autoconf; ./configure; make; sudo make install; cd ..
    - name: Install EUDAQ
      shell: bash -l {0}
      run: |
        source tests/setup_eudaq.sh
    - name: Install package
      shell: bash -l {0}
      run: |
        pip install -e .
    - name: Test
      shell: bash -l {0}
      run: |
        cd tests
        export QT_DEBUG_PLUGINS=1
        pytest -s -v

